# https://stackoverflow.com/questions/41509608/how-do-i-deploy-nuget-packages-in-travis-ci
# https://docs.travis-ci.com/user/languages/csharp/
# https://travis-ci.com/bilal-fazlani/commanddotnet/builds/142334958/config

env:
    APPNAME=DNX.Helpers
    CONFIGURATION=Release
    NUGET_API_URL=https://www.nuget.org/api/v2/package

git:
  depth: 1
  quiet: true

solution: $APPNAME.sln

language: csharp
mono: none

stages:
  - name: build
  - name: deploy
    # if: branch = master
  - name: release
    # if: branch = master

jobs:
  include:
    #----- Build and Test -----#
    - stage: build
    - name: OSX
      os: osx
      dotnet: 2.2.207
      install: dotnet restore
      script: dotnet test -v normal

    - name: Linux
      os: linux
      dotnet: 2.2.102
      install: dotnet restore
      script: dotnet test -v normal

    - name: Windows
      os: windows
      install: dotnet restore
      script: dotnet test -v normal

#    #----- Deploy -----#
#    - stage: deploy
#    - name: NuGet
#      script: skip
#      deploy:
#      - provider: script
#        cleanup: false
#        script: dotnet nuget push $APPNAME/bin/$CONFIGURATION/$APPNAME.*.nupkg -s $NUGET_API_URL -k $NUGET_API_KEY --no-service-endpoint
#
#    #----- Release -----#
#    - stage: release
#    - name: GitHub
#      script: skip
#      deploy:
#      - provider: releases
#        cleanup: false
#        api_key: $GITHUB_TOKEN







#script:
#  - dotnet build -c $CONFIGURATION
#  - dotnet test -v normal
#  - dotnet pack -c $CONFIGURATION
#  # - ls -laR ./$APPNAME
