# https://stackoverflow.com/questions/41509608/how-do-i-deploy-nuget-packages-in-travis-ci
# https://docs.travis-ci.com/user/languages/csharp/

env:
    APPNAME=DNX.Helpers
    CONFIGURATION=Release
    NUGET_API_URL=https://www.nuget.org/api/v2/package
    NUNIT_RUNNERS_VERSION=3.10.0

language: csharp
mono: none
dotnet: 2.2.102

solution: $APPNAME.sln

install:
  - dotnet restore

script:
  - dotnet build -c $CONFIGURATION
  - dotnet test -v normal
  - dotnet pack -c $CONFIGURATION
  # - ls -laR ./$APPNAME

deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push $APPNAME/bin/$CONFIGURATION/$APPNAME.*.nupkg -s $NUGET_API_URL -k $NUGET_API_KEY --no-service-endpoint
  on:
    branch: master
