# https://stackoverflow.com/questions/41509608/how-do-i-deploy-nuget-packages-in-travis-ci
# https://docs.travis-ci.com/user/languages/csharp/
# https://travis-ci.com/bilal-fazlani/commanddotnet/builds/142334958/config

env:
    APPNAME=DNX.Helpers
    CONFIGURATION=Release
    NUGET_API_URL=https://www.nuget.org/api/v2/package

git:
  depth: false

solution: $APPNAME.sln

language: csharp
mono: none

stages:
  - name: Build and Test
  - name: Deploy
    # if: branch = master

jobs:
  include:
    #----- Build and Test -----#
    - stage: Build and Test
      - name: Build on OSX
        os: osx
        dotnet: 2.2.207
        install: dotnet restore
        script: dotnet test -v normal

      - name: Build on Linux
        os: linux
        dotnet: 2.2.102
        install: dotnet restore
        script: dotnet test -v normal

      - name: Build on Windows
        os: windows
        install: dotnet restore
        script: dotnet test -v normal

    #----- Deploy -----#
    - stage: Deploy
        script: skip
        skip_cleanup: true
      - name: NuGet Deploy
        deploy:
        - provider: script
          script: dotnet nuget push $APPNAME/bin/$CONFIGURATION/$APPNAME.*.nupkg -s $NUGET_API_URL -k $NUGET_API_KEY --no-service-endpoint

      - name: GitHub Release
        deploy:
        - provider: releases
          api_key: $GITHUB_TOKEN
