# https://stackoverflow.com/questions/41509608/how-do-i-deploy-nuget-packages-in-travis-ci
# https://docs.travis-ci.com/user/languages/csharp/
# https://travis-ci.com/bilal-fazlani/commanddotnet/builds/142334958/config
# https://travis-ci.com/bilal-fazlani/commanddotnet/builds/142334958/config

env:
    APPNAME=DNX.Helpers
    CONFIGURATION=Release
    NUGET_API_URL=https://www.nuget.org/api/v2/package

git:
  depth: false

solution: $APPNAME.sln

language: csharp
mono: none

stages:
  - name: Build and Test
  - name: Deploy

jobs:
  include:
    #----- Build and Test -----#
    - stage: Build and Test
      name: Build on linux
      os: linux
      dotnet: 2.2.102
      install: dotnet restore
      script: dotnet test -v normal

    #----- Deploy -----#
    - stage: Deploy
      if: branch = master
      name: NuGet Deploy
      deploy:
        provider: script
        skip_cleanup: true
        script: dotnet nuget push $APPNAME/bin/$CONFIGURATION/$APPNAME.*.nupkg -s $NUGET_API_URL -k $NUGET_API_KEY --no-service-endpoint

      name: GitHub Release
      deploy:
        provider: releases
        skip_cleanup: true
        api_key: $GITHUB_OAUTH_TOKEN




#deploy:
#  skip_cleanup: true
#  provider: script
#  script: dotnet nuget push $APPNAME/bin/$CONFIGURATION/$APPNAME.*.nupkg -s $NUGET_API_URL -k $NUGET_API_KEY --no-service-endpoint
#  on:
#    branch: master


# - dotnet build -c $CONFIGURATION
# - dotnet test -v normal
# - dotnet pack -c $CONFIGURATION
# - ls -laR ./$APPNAME
