// Code generated by a Template
using System;
using DNX.Helpers.Maths;
using DNX.Helpers.Maths.BuiltInTypes;
using NUnit.Framework;
using Test.DNX.Helpers.Maths.BuiltInTypes.TestsDataSource;

namespace Test.DNX.Helpers.Maths.BuiltInTypes
{
    [TestFixture]
    public class MathsInt32ExtensionsTests
    {
        [TestCaseSource(typeof(MathsInt32ExtensionsTestsSource), "IsBetween_Default")]
        public bool IsBetween_Default(int value, int min, int max)
        {
            return value.IsBetween(min, max);
        }

        [TestCaseSource(typeof(MathsInt32ExtensionsTestsSource), "IsBetween_BoundsType")]
        public bool IsBetween_BoundsType(int value, int min, int max, IsBetweenBoundsType boundsType)
        {
            return value.IsBetween(min, max, boundsType);
        }

        [TestCaseSource(typeof(MathsInt32ExtensionsTestsSource), "IsBetweenEither_Default")]
        public bool IsBetweenEither_Default(int value, int min, int max)
        {
            return value.IsBetweenEither(min, max);
        }

        [TestCaseSource(typeof(MathsInt32ExtensionsTestsSource), "IsBetweenEither_BoundsType")]
        public bool IsBetweenEither_BoundsType(int value, int min, int max, IsBetweenBoundsType boundsType)
        {
            return value.IsBetweenEither(min, max, boundsType);
        }

        [TestCaseSource(typeof(MathsInt32ExtensionsTestsSource), "IsBetween")]
        public bool IsBetween(int value, int min, int max, bool allowEitherOrder, IsBetweenBoundsType boundsType)
        {
            return value.IsBetween(min, max, allowEitherOrder, boundsType);
        }

        [TestCaseSource(typeof(MathsInt32ExtensionsTestsSource), "GetLowerBound")]
        public int GetLowerBound(int min, int max, bool allowEitherOrder)
        {
            return MathsInt32Extensions.GetLowerBound(min, max, allowEitherOrder);
        }

        [TestCaseSource(typeof(MathsInt32ExtensionsTestsSource), "GetUpperBound")]
        public int GetUpperBound(int min, int max, bool allowEitherOrder)
        {
            return MathsInt32Extensions.GetUpperBound(min, max, allowEitherOrder);
        }
        
        [TestCaseSource(typeof(MathsInt32ExtensionsTestsSource), "ValueToHexString")]
        public string Test_ValueToHexString(int value)
        {
            return value.ToHexString();
        }

        [TestCaseSource(typeof(MathsInt32ExtensionsTestsSource), "ValuesToHexString")]
        public string Test_ValuesToHexString(int[] values)
        {
            return values.ToHexString();
        }
    }
}
