// Code generated by a Template
using System;
using DNX.Helpers.Maths;
using DNX.Helpers.Maths.BuiltInTypes;
using NUnit.Framework;
using Test.DNX.Helpers.Maths.BuiltInTypes.TestsDataSource;

namespace Test.DNX.Helpers.Maths.BuiltInTypes
{
    [TestFixture]
    public class MathsByteExtensionsTests
    {
        [TestCaseSource(typeof(MathsByteExtensionsTestsSource), "IsBetween_Default")]
        public bool IsBetween_Default(byte value, byte min, byte max)
        {
            return value.IsBetween(min, max);
        }

        [TestCaseSource(typeof(MathsByteExtensionsTestsSource), "IsBetween_BoundsType")]
        public bool IsBetween_BoundsType(byte value, byte min, byte max, IsBetweenBoundsType boundsType)
        {
            return value.IsBetween(min, max, boundsType);
        }

        [TestCaseSource(typeof(MathsByteExtensionsTestsSource), "IsBetweenEither_Default")]
        public bool IsBetweenEither_Default(byte value, byte min, byte max)
        {
            return value.IsBetweenEither(min, max);
        }

        [TestCaseSource(typeof(MathsByteExtensionsTestsSource), "IsBetweenEither_BoundsType")]
        public bool IsBetweenEither_BoundsType(byte value, byte min, byte max, IsBetweenBoundsType boundsType)
        {
            return value.IsBetweenEither(min, max, boundsType);
        }

        [TestCaseSource(typeof(MathsByteExtensionsTestsSource), "IsBetween")]
        public bool IsBetween(byte value, byte min, byte max, bool allowEitherOrder, IsBetweenBoundsType boundsType)
        {
            return value.IsBetween(min, max, allowEitherOrder, boundsType);
        }

        [TestCaseSource(typeof(MathsByteExtensionsTestsSource), "GetLowerBound")]
        public byte GetLowerBound(byte min, byte max, bool allowEitherOrder)
        {
            return MathsByteExtensions.GetLowerBound(min, max, allowEitherOrder);
        }

        [TestCaseSource(typeof(MathsByteExtensionsTestsSource), "GetUpperBound")]
        public byte GetUpperBound(byte min, byte max, bool allowEitherOrder)
        {
            return MathsByteExtensions.GetUpperBound(min, max, allowEitherOrder);
        }
        
        [TestCaseSource(typeof(MathsByteExtensionsTestsSource), "ValueToHexString")]
        public string Test_ValueToHexString(byte value)
        {
            return value.ToHexString();
        }

        [TestCaseSource(typeof(MathsByteExtensionsTestsSource), "ValuesToHexString")]
        public string Test_ValuesToHexString(byte[] values)
        {
            return values.ToHexString();
        }
    }
}
