// Code generated by a Template
using System;
using DNX.Helpers.Maths;
using DNX.Helpers.Maths.BuiltInTypes;
using NUnit.Framework;
using Test.DNX.Helpers.Maths.BuiltInTypes.TestsDataSource;

namespace Test.DNX.Helpers.Maths.BuiltInTypes
{
    [TestFixture]
    public class MathsInt16ExtensionsTests
    {
        [TestCaseSource(typeof(MathsInt16ExtensionsTestsSource), "IsBetween_Default")]
        public bool IsBetween_Default(short value, short min, short max)
        {
            return value.IsBetween(min, max);
        }

        [TestCaseSource(typeof(MathsInt16ExtensionsTestsSource), "IsBetween_BoundsType")]
        public bool IsBetween_BoundsType(short value, short min, short max, IsBetweenBoundsType boundsType)
        {
            return value.IsBetween(min, max, boundsType);
        }

        [TestCaseSource(typeof(MathsInt16ExtensionsTestsSource), "IsBetweenEither_Default")]
        public bool IsBetweenEither_Default(short value, short min, short max)
        {
            return value.IsBetweenEither(min, max);
        }

        [TestCaseSource(typeof(MathsInt16ExtensionsTestsSource), "IsBetweenEither_BoundsType")]
        public bool IsBetweenEither_BoundsType(short value, short min, short max, IsBetweenBoundsType boundsType)
        {
            return value.IsBetweenEither(min, max, boundsType);
        }

        [TestCaseSource(typeof(MathsInt16ExtensionsTestsSource), "IsBetween")]
        public bool IsBetween(short value, short min, short max, bool allowEitherOrder, IsBetweenBoundsType boundsType)
        {
            return value.IsBetween(min, max, allowEitherOrder, boundsType);
        }

        [TestCaseSource(typeof(MathsInt16ExtensionsTestsSource), "GetLowerBound")]
        public short GetLowerBound(short min, short max, bool allowEitherOrder)
        {
            return MathsInt16Extensions.GetLowerBound(min, max, allowEitherOrder);
        }

        [TestCaseSource(typeof(MathsInt16ExtensionsTestsSource), "GetUpperBound")]
        public short GetUpperBound(short min, short max, bool allowEitherOrder)
        {
            return MathsInt16Extensions.GetUpperBound(min, max, allowEitherOrder);
        }
        
        [TestCaseSource(typeof(MathsInt16ExtensionsTestsSource), "ValueToHexString")]
        public string Test_ValueToHexString(short value)
        {
            return value.ToHexString();
        }

        [TestCaseSource(typeof(MathsInt16ExtensionsTestsSource), "ValuesToHexString")]
        public string Test_ValuesToHexString(short[] values)
        {
            return values.ToHexString();
        }
    }
}
