// Code generated by a Template
using System;
using DNX.Helpers.Maths;
using DNX.Helpers.Maths.BuiltInTypes;
using NUnit.Framework;
using Test.DNX.Helpers.Maths.BuiltInTypes.TestsDataSource;

namespace Test.DNX.Helpers.Maths.BuiltInTypes
{
    [TestFixture]
    public class MathsUInt16ExtensionsTests
    {
        [TestCaseSource(typeof(MathsUInt16ExtensionsTestsSource), "IsBetween_Default")]
        public bool IsBetween_Default(ushort value, ushort min, ushort max)
        {
            return value.IsBetween(min, max);
        }

        [TestCaseSource(typeof(MathsUInt16ExtensionsTestsSource), "IsBetween_BoundsType")]
        public bool IsBetween_BoundsType(ushort value, ushort min, ushort max, IsBetweenBoundsType boundsType)
        {
            return value.IsBetween(min, max, boundsType);
        }

        [TestCaseSource(typeof(MathsUInt16ExtensionsTestsSource), "IsBetweenEither_Default")]
        public bool IsBetweenEither_Default(ushort value, ushort min, ushort max)
        {
            return value.IsBetweenEither(min, max);
        }

        [TestCaseSource(typeof(MathsUInt16ExtensionsTestsSource), "IsBetweenEither_BoundsType")]
        public bool IsBetweenEither_BoundsType(ushort value, ushort min, ushort max, IsBetweenBoundsType boundsType)
        {
            return value.IsBetweenEither(min, max, boundsType);
        }

        [TestCaseSource(typeof(MathsUInt16ExtensionsTestsSource), "IsBetween")]
        public bool IsBetween(ushort value, ushort min, ushort max, bool allowEitherOrder, IsBetweenBoundsType boundsType)
        {
            return value.IsBetween(min, max, allowEitherOrder, boundsType);
        }

        [TestCaseSource(typeof(MathsUInt16ExtensionsTestsSource), "GetLowerBound")]
        public ushort GetLowerBound(ushort min, ushort max, bool allowEitherOrder)
        {
            return MathsUInt16Extensions.GetLowerBound(min, max, allowEitherOrder);
        }

        [TestCaseSource(typeof(MathsUInt16ExtensionsTestsSource), "GetUpperBound")]
        public ushort GetUpperBound(ushort min, ushort max, bool allowEitherOrder)
        {
            return MathsUInt16Extensions.GetUpperBound(min, max, allowEitherOrder);
        }
        
        [TestCaseSource(typeof(MathsUInt16ExtensionsTestsSource), "ValueToHexString")]
        public string Test_ValueToHexString(ushort value)
        {
            return value.ToHexString();
        }

        [TestCaseSource(typeof(MathsUInt16ExtensionsTestsSource), "ValuesToHexString")]
        public string Test_ValuesToHexString(ushort[] values)
        {
            return values.ToHexString();
        }
    }
}
