// Code generated by a Template
using System;
using DNX.Helpers.Maths;
using DNX.Helpers.Maths.BuiltInTypes;
using NUnit.Framework;
using Test.DNX.Helpers.Maths.BuiltInTypes.TestsDataSource;

namespace Test.DNX.Helpers.Maths.BuiltInTypes
{
    [TestFixture]
    public class MathsUInt64ExtensionsTests
    {
        [TestCaseSource(typeof(MathsUInt64ExtensionsTestsSource), "IsBetween_Default")]
        public bool IsBetween_Default(ulong value, ulong min, ulong max)
        {
            return value.IsBetween(min, max);
        }

        [TestCaseSource(typeof(MathsUInt64ExtensionsTestsSource), "IsBetween_BoundsType")]
        public bool IsBetween_BoundsType(ulong value, ulong min, ulong max, IsBetweenBoundsType boundsType)
        {
            return value.IsBetween(min, max, boundsType);
        }

        [TestCaseSource(typeof(MathsUInt64ExtensionsTestsSource), "IsBetweenEither_Default")]
        public bool IsBetweenEither_Default(ulong value, ulong min, ulong max)
        {
            return value.IsBetweenEither(min, max);
        }

        [TestCaseSource(typeof(MathsUInt64ExtensionsTestsSource), "IsBetweenEither_BoundsType")]
        public bool IsBetweenEither_BoundsType(ulong value, ulong min, ulong max, IsBetweenBoundsType boundsType)
        {
            return value.IsBetweenEither(min, max, boundsType);
        }

        [TestCaseSource(typeof(MathsUInt64ExtensionsTestsSource), "IsBetween")]
        public bool IsBetween(ulong value, ulong min, ulong max, bool allowEitherOrder, IsBetweenBoundsType boundsType)
        {
            return value.IsBetween(min, max, allowEitherOrder, boundsType);
        }

        [TestCaseSource(typeof(MathsUInt64ExtensionsTestsSource), "GetLowerBound")]
        public ulong GetLowerBound(ulong min, ulong max, bool allowEitherOrder)
        {
            return MathsUInt64Extensions.GetLowerBound(min, max, allowEitherOrder);
        }

        [TestCaseSource(typeof(MathsUInt64ExtensionsTestsSource), "GetUpperBound")]
        public ulong GetUpperBound(ulong min, ulong max, bool allowEitherOrder)
        {
            return MathsUInt64Extensions.GetUpperBound(min, max, allowEitherOrder);
        }
        
        [TestCaseSource(typeof(MathsUInt64ExtensionsTestsSource), "ValueToHexString")]
        public string Test_ValueToHexString(ulong value)
        {
            return value.ToHexString();
        }

        [TestCaseSource(typeof(MathsUInt64ExtensionsTestsSource), "ValuesToHexString")]
        public string Test_ValuesToHexString(ulong[] values)
        {
            return values.ToHexString();
        }
    }
}
